[package]
name = "simulink-binder"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
paste = "1.0.5"
proc-macro2 = "1.0.28"
quote = "1.0.9"
regex = "1.5.4"
syn = "1.0.74"

